### ISSUE TITLE
Is it possible to call mysqlimport ?

### ISSUE THREAD

**Issue by jonathanBieler** [datacharmer/dbdeployer#101]
I'm trying to import data from Ensembl (genomic) into a sandbox but in their instruction they use mysqlimport at some point to import a bunch if text files, and I haven't found a way to do it with dbdeployer. Is there a way to call mysqlimport on my sandbox or do I need to write my own `LOAD DATA` statements and execute them with `~/sandboxes/XYZ/use` ? 

Sorry if it's a dumb question, I'm not super familiar with mysql.

**Comment by datacharmer** [comment]
Each single sandbox has a script called `my`, to which you add the remainder of the utility name you want to call.
In your case, it will be `~/sandboxes/XYZ/my sqlimport [options]`
Notice the space between `my` and `sqlimport`
See [Sandbox management](https://github.com/datacharmer/dbdeployer#sandbox-management) for more info

**Comment by jonathanBieler** [comment]
Perfect, I've searched through the doc but I somehow missed it. Thanks for the quick answer!
