### ISSUE TITLE
Unable to unpack Percona-Server 8.0.18-9.

### ISSUE THREAD

**Issue by jfg956** [datacharmer/dbdeployer#103]
**Describe the bug**
After downloading Percona-Server 8.0.18-9 for debian, I am unable to unpack.

**To Reproduce**
$ p="https://www.percona.com/downloads/Percona-Server-8.0"
$ l="Linux.x86_64.ssl102.deb.tar.gz"
$ p2="Percona-Server-8.0.18-9"
$ wget $p/$p2/binary/tarball/${p2}-$l
[...]
$ dbdeployer unpack --prefix=ps_ ${p2}-${l}
validation for Percona-Server-8.0.18-9-Linux.x86_64.ssl102.deb.tar.gz failed: inner directory name different from tarball name
Expected: Percona-Server-8.0.18-9-Linux.x86_64.ssl102.deb - Found: Percona-Server-8.0.18-9-Linux.x86_64.ssl102

**Expected behavior**
Unpack should succeed.

**Environment:**
$ uname -a
Linux xxx-amd64 #1 SMP Debian 4.9.189-3+deb9u2 (2019-11-11) x86_64 GNU/Linux

 $ dbdeployer --version
dbdeployer version 1.42.0

**Additional context**
This works:

$ cp Percona-Server-8.0.18-9-Linux.x86_64.ssl102.{,deb}.tar.gz
$ dbdeployer unpack --prefix=ps_ Percona-Server-8.0.18-9-Linux.x86_64.ssl102.tar.gz

**Comment by jfg956** [comment]
https://jira.percona.com/browse/PS-6857

**Comment by datacharmer** [comment]
Hi,
Thanks for reporting this issue, and fo filing the problem with Percona.
This is a Percona packaging problem that has been reported before (Issue #96).
After that episode, I added the error message that tells what the problem really is. 

I could try to make dbdeployer find a workaround in this case, but it is really a misnamed package issue that should be solved upstream.

However, if you or someone else want to submit a PR with a fix (that doesn't break other code) I will gladly look into it.
