### ISSUE TITLE
make available via homebrew

### ISSUE THREAD

**Issue by jpike88** [datacharmer/dbdeployer#104]
Would be nice for an easier install process :)

**Comment by datacharmer** [comment]
I concur that it would be nice. However, I have no idea about what to do to make it happen. I'd like some help from who knows the process or from someone who deals with the installation of other packages.

In the meantime, notice that once you have installed the first time, you can upgrade using
`dbdeployer update --verbose`

**Comment by datacharmer** [comment]
Note that dbdeployer, like most of Go applications, is available through [gobinaries](https://gobinaries.com)
```
$ curl -sf https://gobinaries.com/datacharmer/dbdeployer | sh
```

**Comment by jpike88** [comment]
That’s nifty, thanks. Though homebrew is the defacto unofficial package manager on Mac... I just read about how to submit your package to home brew and it actually looks pretty straightforward, you’ve already compiled a binary for Mac. I’d do it for you but I would then have my name over the pull request instead of yours

**Comment by datacharmer** [comment]
Just point me to the procedure, and I will do it.

**Comment by jpike88** [comment]
https://tech.cars.com/distributing-your-home-grown-tools-to-the-masses-with-homebrew-acb7a62518a8

This guide should take you through it quickly enough without having to dissect homebrew documentation

**Comment by datacharmer** [comment]
Sorry, I have been busy with other priorities. Feel free to submit the package to Homebrew on your name, and document the formula here.
To make things easier, the [releases page](https://github.com/datacharmer/dbdeployer/releases) now includes the SHA256 signatures for all compiled artifacts.

**Comment by morgo** [comment]
It is a full-time job trying to get new formulas merged into homebrew core. I ended up giving up on [my last attempt](https://github.com/Homebrew/homebrew-core/pull/37634).

For whoever picks this up, I would recommend[ creating a custom tap to start with](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap). It's really not that much more effort on users to install from a tap.

**Comment by jmcvaughn** [comment]
I've submitted a PR: https://github.com/Homebrew/homebrew-core/pull/60719

Note that homebrew-core doesn't like binaries, so the pre-built binaries available _would_ go in homebrew-cask. However, I don't believe there is a way to pull additional files with Casks, so there wouldn't be a way to install docs/dbdeployer_completion.sh.

Note that macOS/Homebrew do not have /etc/bash_completion, /usr/local/etc/bash_completion or /etc/profile.d/bash_completion.sh, so you'll still get errors running `dbdeployer init`; that's a separate issue though.

**Comment by jmcvaughn** [comment]
This is now merged: https://github.com/Homebrew/homebrew-core/commit/e1d42dd95c3181abf79b0b09de384f0fdbf5f29b
