### ISSUE TITLE
Says I don't have mysql

### ISSUE THREAD

**Issue by jpike88** [datacharmer/dbdeployer#105]
```ERROR reading directory /Users/joshua/opt/mysql: open /Users/joshua/opt/mysql: no such file or directory```

I installed mysql using the package installer for Mac that you download from their official site. It installs mysql here:

```/usr/local/ ```

Am now trying to install mysql with homebrew instead

**Comment by datacharmer** [comment]
dbdeployer works with **tarballs**, not native packages. You don't need to have MySQL installed to run dbdeployer: its purpose is to deploy **side** servers, i.e. servers that run separately from existing ones.

I don't know what command you used to get that error.

The operations to get started are:

1. Get a tarball (use `dbdeployer downloads list` and `dbdeployer downloads get`)
2. expand the tarball (`dbdeployer unpack`)
3. deploy the server (`dbdeployer deploy single x.x.xx`)

The README explains each of the operations in detail

**Comment by jpike88** [comment]
ahhh it manages everything. thanks

**Comment by jpike88** [comment]
might be worth throwing a warning message for noobies

**Comment by datacharmer** [comment]
If you tell me which command you used to get the unexpected result, it might be easier to know where to put the warning you want.

As it is, dbdeployer throws plenty of warnings about wrong behavior, but I guess it can improve.

Reading some of the README may also help.
