### ISSUE TITLE
Custom 'CHANGE MASTER TO' params

### ISSUE THREAD

**Issue by shlomi-noach** [datacharmer/dbdeployer#107]
**Is your feature request related to a problem? Please describe.**
I wish to set up my replicas with specific parameters. e.g. `MASTER_CONNECT_RETRY=1` (as opposed to the default `60`) or `MASTER_RETRY_COUNT=<somevalue>`

The two specific replication params I mentioned are essential for quick(er) failure resolution.

**Describe the solution you'd like**
`dbdeployer deploy` to support `--change-master-options` [stringArray], similarly to `--my-cnf-options`. Example usage:

```shell
$ dbdeployer deploy replication 5.7.26 \
  --gtid \
  --my-cnf-options="slave_net_timeout=2" \
  --change-master-options="MASTER_CONNECT_RETRY=1" \
  --change-master-options="MASTER_RETRY_COUNT=10" \
```

**Describe alternatives you've considered**
the current alternative is to (post `deploy`) run `stop slave; change master to... ; start slave` on all replicas.

Thank you for your consideration.

**Comment by datacharmer** [comment]
Thanks for this feature request.
It can be added easily.
In the meantime, here's a workaround to achieve the goal with the current features:

0. (optional) `dbdeployer defaults templates list replication`
1. `dbdeployer defaults templates show init_slaves_template > /tmp/init.tmpl`
2. Edit the file `/tmp/init.tmpl` to include the options you'd like.
3. Run replication as 
```
dbdeployer deploy replication 5.7.26 \
  --gtid \
  --my-cnf-options="slave_net_timeout=2" \
  --use-template=init_slave_template:/tmp/init.tmpl
```
The file `initialize_slaves` will be generated (and later run) with the changes you have added to the template. See [Sandbox Customization](https://github.com/datacharmer/dbdeployer#sandbox-customization) for more info.

**Comment by shlomi-noach** [comment]
Thank you, I can confirm the workaround works, per https://github.com/openark/orchestrator-ci-env/pull/17

**Comment by datacharmer** [comment]
Implemented in [v1.49.0](https://github.com/datacharmer/dbdeployer/releases/tag/v1.49.0)

**Comment by shlomi-noach** [comment]
Thank you for releasing v1.49.0! Just as addendum (possibly worth opening a new issue), `dbdeployer deploy --help` does not indicate the new `--change-master-options` flags, although I can confirm they work.

**Comment by datacharmer** [comment]
Thanks for confirming that the new flags works.

As for the help, the flag `--change-master-options` belongs to the sub-command `deploy replication`, not just `deploy`, as it is not applicable to single sandboxes. Similarly to the flag `--prompt` that applies to single deployments but not to replication.

**Comment by shlomi-noach** [comment]
Perfect, thank you!
