### ISSUE TITLE
Panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by RicLzPt** [datacharmer/dbdeployer#108]
**Describe the bug**
Hi,
I try to run command and error occur
I have the binary file in folder and other folders created correctly

**To Reproduce**
1. Run the command '...'
in folder that contains dbdeployer-1.50.0.linux run
./dbdeployer-1.50.0.linux deploy single 5.7.26 --sandbox-binary /media/riclzpt/Dados/Mysql/mysql-5.7.26.tar.xz --sandbox-home /media/riclzpt/Dados/Mysql/sandboxes

2. See error '....'
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x58f328]

goroutine 1 [running]:
github.com/datacharmer/dbdeployer/common.DirExists(0xc000100c80, 0x35, 0x2)
	/Users/gmax/go/src/github.com/datacharmer/dbdeployer/common/fileutil.go:347 +0x98
github.com/datacharmer/dbdeployer/cmd.fillSandboxDefinition(0xd23e00, 0xc000068370, 0x1, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/gmax/go/src/github.com/datacharmer/dbdeployer/cmd/single.go:248 +0x59e
github.com/datacharmer/dbdeployer/cmd.singleSandbox(0xd23e00, 0xc000068370, 0x1, 0x5)
	/Users/gmax/go/src/github.com/datacharmer/dbdeployer/cmd/single.go:431 +0xc8
github.com/spf13/cobra.(*Command).execute(0xd23e00, 0xc000068320, 0x5, 0x5, 0xd23e00, 0xc000068320)
	/Users/gmax/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0xd23680, 0x928d4f, 0x8, 0xd5eaa0)
	/Users/gmax/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/gmax/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/datacharmer/dbdeployer/cmd.Execute()
	/Users/gmax/go/src/github.com/datacharmer/dbdeployer/cmd/root.go:65 +0x5d1
main.main()
	/Users/gmax/go/src/github.com/datacharmer/dbdeployer/main.go:25 +0x25

**Expected behavior**
Run without a error

**NO Screenshots**
If applicable, copy and paste the command and the output. Do not use screen shots, unless they add value to the report.  Text that can be edited is preferred to graphics.

**Environment:**
 - OS: Pop OS 20.04
 - dbdeployer 1.50.0
 - tarball full name mysql-5.7.26.tar.xz
 - tarball origin (from where it was downloaded) 

**Hardware: (if applicable)**
 - Free storage 230GB
 - Total RAM 8GB

**Additional context**

**Comment by datacharmer** [comment]
Please give info about which command you were running, and all the details you left blank in your report

**Comment by RicLzPt** [comment]
> Please give info about which command you were running, and all the details you left blank in your report

Sorry, i clicked and posted before complete information. I edited it
Excuse my poor english

**Comment by datacharmer** [comment]
I see `--sandbox-binary /media/riclzpt/Dados/Mysql/mysql-5.7.26.tar.xz`
Sandbox binary should be a directory, but it is been given a tarball.

The way it works is:

1. `mkdir $HOME/opt/mysql` (the default sandbox binary)
2. `dbdeployer unpack /media/riclzpt/Dados/Mysql/mysql-5.7.26.tar.xz`
3. `dbdeployer deploy single 5.7.26`

If you don't want the default sandbox binary, you need to

1. `mkdir /some/path`
2. `dbdeployer --sandbox-binary=/some/path unpack /media/riclzpt/Dados/Mysql/mysql-5.7.26.tar.xz`
3. `dbdeployer  --sandbox-binary=/some/path deploy single 5.7.26`

**Comment by RicLzPt** [comment]
> I see `--sandbox-binary /media/riclzpt/Dados/Mysql/mysql-5.7.26.tar.xz`
> Sandbox binary should be a directory, but it is been given a tarball.
> 
> The way it works is:
> 
> 1. `mkdir $HOME/opt/mysql` (the default sandbox binary)
> 2. `dbdeployer unpack /media/riclzpt/Dados/Mysql/mysql-5.7.26.tar.xz`
> 3. `dbdeployer deploy single 5.7.26`
> 
> If you don't want the default sandbox binary, you need to
> 
> 1. `mkdir /some/path`
> 2. `dbdeployer --sandbox-binary=/some/path unpack /media/riclzpt/Dados/Mysql/mysql-5.7.26.tar.xz`
> 3. `dbdeployer  --sandbox-binary=/some/path deploy single 5.7.26`

Thanks a lot!!!
Here in Brazil, we called this "orelhada" (my bad, kkkk)

Dbdeployer runs fine!
I did this
- I created  Mysql dir in my home dir
- I created  binaries, logs and sandbox dir in Mysql dir
- I downloaded dbdeployer in Mysql dir, extrated and renamed to dbdeployer and setted to executable
- and ran:
./dbdeployer downloads get mysql-8.0.20-linux-x86_64-minimal.tar.xz
./dbdeployer --sandbox-binary ./binaries/ unpack ./mysql-8.0.20-linux-x86_64-minimal.tar.xz
./dbdeployer deploy single 8.0.20 --sandbox-binary ./binaries/ --sandbox-home ./sandbox/ --log-directory ./logs/

Just this

best regards

**Comment by datacharmer** [comment]
Panic error fixed in version 1.50.1
