### ISSUE TITLE
Upgrading to 1.51 throws `error while filling the sandbox definition`

### ISSUE THREAD

**Issue by vgrippa** [datacharmer/dbdeployer#109]
**Describe the bug**
After upgrading to 1.51 is not possible to use the command below:

`dbdeployer  deploy single /opt/mysql/8.0.19/ --port=45005`

**To Reproduce**
`$ dbdeployer  deploy single /opt/mysql/8.0.19/ --port=45005
error while filling the sandbox definition: sandbox binary /home/vinicius.grippa/opt/mysql is not a directory or doesn't exist`

Same with:
`dbdeployer  deploy single --sandbox-binary=/opt/mysql/8.0.19/
this command requires the MySQL version (x.xx[.xx]) as argument`

**Expected behavior**
Set the sandbox

**Environment:**
 - OS: Centos 7
 - dbdeployer version 1.51

**Additional context**
Downgrade to 1.49 works.

**Comment by datacharmer** [comment]
Thanks for this report.

The error is due to the `$SANDBOX_BINARY` or `--sandbox-binary` to be undefined. Even if you give a full path, the directory indicated by `$SANDBOX_BINARY` needs to exist.

Please try
```
$ dbdeployer --sandbox-binary=/opt/mysql  deploy single  8.0.19
```

or
```
$ export SANBDOX_BINARY=/opt/mysql
$ dbdeployer  deploy single  8.0.19
```

**Comment by datacharmer** [comment]
Please note that the behavior in 1.49.0 was working by chance, but it was wrong: it was creating a panic when a  non-directory was given through `--sandbox-directory`.

**Comment by vgrippa** [comment]
Hi Giuseppe,

I tried both ways with 1.51 version and it didn't work:

`
[PROD-SER] [vinicius.grippa@bm-support01 ~]$ dbdeployer deploy multiple --sandbox-binary=/opt/mysql/5.7.29/ -n 2
this command requires the MySQL version (x.xx[.xx]) as argument

[PROD-SER] [vinicius.grippa@bm-support01 ~]$ export SANBDOX_BINARY=/opt/mysql
[PROD-SER] [vinicius.grippa@bm-support01 ~]$ dbdeployer deploy multiple --sandbox-binary=/opt/mysql/5.7.29/ -n 2
this command requires the MySQL version (x.xx[.xx]) as argument
`

**Comment by datacharmer** [comment]
Hi Vinicius,
The problem in your command is that you include the version directory `5.7.29` in `--sandbox-directory`.

The sandbox directory is the place where all the versions are found, not the path to a single expanded tarball.

If you set $SANDBOX_BINARY, you don't need to use `--sandbox-directory`

**Comment by datacharmer** [comment]
your command should be
```
$ dbdeployer --sandbox-binary=/opt/mysql   deploy multiple 5.7.29 -n 2
```

**Comment by vgrippa** [comment]
Giuseppe,

As we spoke on Slack your suggestion worked. I'm leaving the command here for future generations in case someone finds the same issue. Thanks for your prompt help!

`$ dbdeployer deploy multiple --sandbox-binary=/opt/mysql/ 5.7.29 -n 2
Installing and starting node 1
. sandbox server started
Installing and starting node 2
. sandbox server started
multiple directory installed in $HOME/sandboxes/multi_msb_5_7_29`
