### ISSUE TITLE
Dbdeployer hosted DBs - How to connect from within Docker containers.

### ISSUE THREAD

**Issue by ChameleonDevil** [datacharmer/dbdeployer#114]
I have now setup the two databases I require, and as advised from previous discussions I moved binaries and sandbox folders so that I have will have all flavors inside the same parent locations.

The databases are hosted in the host operating system (Ubuntu 20.04), where I also have seperate websites setup inside Docker - Docker-compose projects with a network.

Before using DbDeployer I always managed to connect to the host OS MySQL databases within the docker containers.

Running this on host OS: (Ubuntu 20.04)
DbDeployer instance: `mysql_sandbox5_7_31`

The latest Linux MySQL version we added last week : v5.7.31
_I edited my.sandbox.cnf_and changed **bind-address=0.0.0.0**_

`mysql -u mynewuser -p -h (myhostipaddress) -P 5731`   - _I am successfully able to connect to the database with my new user that I GRANT PRIVILEGES ON my databases_

_Also using DBeaver Windows client to connect via SSH along with the MySQL credentials (host/port/username) so I am able to connect like that_

## Question
Why am I not able to connect to the database from within docker containers?
`docker exec -ti web-server-container-with-mysql-client bash`
`mysql -u mynewuser -p -h 192.168.1.105 -P 5731`

It takes about 2+ minutes to connect, then eventually fails with `ERROR 2003 (HY000): Can't connect to MySQL server on '192.168.1.105' (110)`

## Update

- (Both DbDeployer databases and Docker containers are hosted on the same IP : 105)
- Also, I created a docker network, and am able to ping other containers, and the host)
`ping localhost`, `ping nginx-proxy` `ping varnish-cache` `ping 192.168.1.105`

I have done an extra test, connecting to a remote  MySQL database from the same Docker Container (where I want to use Dbdeployed instance) on that host where DbDeployer is installed (IP 105), and was able to connect to a database on my VirtualBox (IP 5) on port 3307.

**Comment by datacharmer** [comment]
By default, sandboxes are tied to `127.%`

Create the sandbox with:
```
dbdeployer deploy single 5.7.31 --remote-access=% --bind-address=0.0.0.0
```
And it can connect from outside 127.0.0.1

**Comment by ChameleonDevil** [comment]
I am unable to get it working: _Note I have my existing sandbox as well that I do not want to remove yet._

       dbdeployer versions
       mysql5.7.30  mysql5.7.31
       
      dbdeployer deploy single --sandbox-directory m2_5731 --remote-access=% --bind-address=0.0.0.0 5.7.31
       
      dbdeployer sandboxes
      m2_5731                  :   single   mysql5.7.31   [5732 ]
      mysql5_7_31              :   single   mysql5.7.31   [5731 ]


- Setup users & DATABASE inside ./m2_5731:
`./m2_5731/use -u root`   _(Default msandbox user do not have CREATE USER privileges)_

       CREATE USER 'magtest'@'%' IDENTIFIED BY 'mypass';   
       CREATE USER 'magtest'@'localhost' IDENTIFIED BY 'mypass';
       CREATE DATABASE testmagtest;
       GRANT ALL PRIVILEGES ON testmagtest.* TO 'magtest'@'%';
       GRANT ALL PRIVILEGES ON testmagtest.* TO 'magtest'@'localhost';
       FLUSH PRIVILEGES;
       exit

From host (not docker container):

       mysql -u magtest -p -h 192.168.1.105 -P 5732` **AND** `mysql -u magtest -p -h 127.0.0.1 -P 5732`
       
       SHOW DATABASES;
       +--------------------+
       | Database           |
      +--------------------+
       | information_schema |
       | testmagtest        |
      +--------------------+
      2 rows in set (0.00 sec)

From docker-container:
_Additional information of Docker as well provided:_
       
       docker-compose ps
                      Name                         Command          State                       Ports
       -------------------------------------------------------------------------------------------------------------------
       nginx-proxy-glo-magento2.3.5          /usr/bin/supervisord   Up      0.0.0.0:443->443/tcp, 0.0.0.0:80->80/tcp
       redis-cache-glo-magento2.3.5          /usr/bin/supervisord   Up      0.0.0.0:6379->6379/tcp
       varnish-cache-glo-magento2.3.5        /usr/bin/supervisord   Up      0.0.0.0:6081->6081/tcp, 0.0.0.0:6082->6082/
       web-server-apache2-glo-magento2.3.5   /usr/bin/supervisord   Up      0.0.0.0:8080->8080/tcp

       docker exec -ti web-server-apache2-glo-magento2.3.5 bash
       mysql -u magento2glolighting -p -h 192.168.1.105 -P 5732
       _**...takes long to fail...**_

       mysql -u magento2glolighting -p -h 127.0.0.1 -P 5732
       **_immediately fails_**
       ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (111)


I also stopped the host installed mysql to make sure it doesn't have an impact:
`sudo service mysql stop`

The only remaining thing I can think of, the firewall blocking to docker container?
_(I don't think the issue is that ports that aren't exposed since its a host side MySQL DbDeployer installation, also I sort of confirmed that because I am able to connect to a **remote** 192.168.1.5 **host MySQL** but **even a MySQL instance inside the docker container inside that remote IP**)_

## Why am I trying to use DbDeployer then and not MySQL docker containers?
From my personal experience MySQL inside Docker-containers for **Magento 2 e-commerce installations** have a huge performance hit compared to just hosting it outside the host.

This Dbdeployer tool seemed perfect for this use-case, since I can then install different versions of MariaDB/MySQL and test Magento 2 installations.

For reference: Magento 1 has limited support for MySQL 5.7 (runs on 5.6), Magento 2.2 runs barely on MySQL 5.7, Magento 2.3(.5) (PHP 7.3) which I am currently testing runs on 5.7.31, then the new new version has zero support for it, runs on MySQL8.0 (PHP 7.4), 

Obviously I need tools to easily test installations with these ridiculous differences.  M2 tends to break so much on every even new minor version.

**Comment by datacharmer** [comment]
Are you sure that the IP address used by Docker is `192.168.*`? 
Unless you have made it so explicitly, Docker IPs are in the range `172.*`
Even though the database is installed in the host, the Docker container can only see it using its own subnet.

```
### HOST
$ dbdeployer deploy single 5.7 --remote-access=% --bind-address=0.0.0.0
# 5.7 => 5.7.31
Database installed in $HOME/sandboxes/msb_5_7_31
run 'dbdeployer usage single' for basic instructions'
. sandbox server started

$ ifconfig | grep inet
        inet 172.18.0.1  netmask 255.255.0.0  broadcast 172.18.255.255
        inet 172.19.0.1  netmask 255.255.0.0  broadcast 172.19.255.255
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        inet 192.168.1.12  netmask 255.255.255.0  broadcast 192.168.1.255
        inet 127.0.0.1  netmask 255.0.0.0


### CONTAINER
$ docker run -ti datacharmer/mysql-sb-full bash
msandbox@12bfa872f25c:~$ ifconfig | grep inet
        inet 172.17.0.2  netmask 255.255.0.0  broadcast 172.17.255.255
        inet 127.0.0.1  netmask 255.0.0.0
msandbox@12bfa872f25c:~$ ./opt/mysql/5.7.26/bin/mysql -h 172.17.0.1 --port 5731 -u msandbox -pmsandbox
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 3
Server version: 5.7.31 MySQL Community Server (GPL)

Copyright (c) 2000, 2019, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> ^DBye
msandbox@12bfa872f25c:~$ exit
```

**Comment by ChameleonDevil** [comment]
I see your point and it does make sense.

The confusion though is I never needed to connect like that.  I have used Docker with Magento 2 installations; and inside the app/etc/env.php I have always used this:  (This is inside the VirtualBox docker container):

         'default' => [
                'host' => '192.168.1.5:3307',
                'dbname' => 'magento2_database',

I have now installed ifconfig inside both containers to compare between the two installations to see if I can see any difference.
_(I also can't recall ever needing to use 172.x network other than inside the Varnish cache configuration)_

Even `docker network inspect networkname` does not have any differences at all.  
(The VB docker installation has network of 172.19.0.*, bridge etc)
(New server docker installation has network of 172.20.0.*, bridge as well)

Trying to connect to host 172.20.0.1 (confirmed on host like you did there - it is also configured as the gateway inside docker network) still fails.

Doing the same thing inside the VirtualBox container with the gateway IP, I am also successfully able to connect; so the good thing I learnt here is now I can update my app/etc/env.php to use the docker container network rather than host IP.

Now just to figure out why it doesn't work, I do not see any differences at all.

**Comment by datacharmer** [comment]
This issue is rapidly morphing into Docker support. Let's try to stick to the topic of dbdeployer.
Using `--remote-access=% --bind-address=0.0.0.0` you can access the database from outside `127.%`.  Whether you are able to see it or not depends on your Docker configuration and/or firewall rules.

There are several ways of using Docker networking. If the one from my previous answer doesn't work, you can try 
`docker run -ti --network=host  image_name bash` and from there using the host real IP. This works in both Linux and MacOS. Be aware that using host network in Docker has side effects. Refer to the [docs](https://docs.docker.com/network/host/) for more

**Comment by ChameleonDevil** [comment]
I apologize that this is extending more and more :(
I am aware this is changing into Docker support because you have confirmed I am supposed to be able to connect to MySQL that way - _at first I thought maybe there are some additional special configurations Dbdeployer required-it seems not._

I will use test containers again which you specified in the other topic (just need to find it again) to see the effect.

**To try to stay on topic of Dbdeployer:**

Functionally, what is `--remote-access` supposed to do?  
Which particular setting does it process for databases?  Is there something I can confirm related to that?
`dbdeployer deploy single --sandbox-directory m2_5731 --remote-access=% --bind-address=0.0.0.0 5.7.31`

I inspected my ./m2_5731 folder and find this:
`./sbdescription.json:   "command-line": "dbdeployer deploy single --sandbox-directory m2_5731 --remote-access=% --bind-address=0.0.0.0 mysql5.7.31"`

So not sure what it targets/updates.

**Comment by datacharmer** [comment]
`--remote-access=%` affects the creation of sandbox users. Instead of making `msandbox@'127.%'`, it makes `msandbox@'%'`.
You can see the effects in the file `grants.mysql`.

**Comment by ChameleonDevil** [comment]
Ok well that is not something I really require then, since I create custom users, with grants specified in my original topic you closed.  In other words, it is still not pointing me in the right direction ;)

Many thanks - again the intention here was just to confirm if there are any special flags I needed to have for the DB to be able to connect - and seeing the `--remote-access` originally I thought this is what I needed.

Ah well, I will continue the struggle.   

Please keep this open, once I have something concrete to update / ask I will do so.

Thanks!

**Comment by ChameleonDevil** [comment]
It was the firewall indeed.  

`ufw allow 5732`
`ufw allow 5731`

I sincerely apologize, I have applied this previously, but then I had a power trip.  It was quite possible that it did not apply the rules on restart, really not sure what happened.  

For your reference, you may also use the IP Address (192.168.* range) as well, just confirmed this again, but it was useful to be shown of the internal docker network.  Not entirely futile exercise (for me at least), for you it was a waste of time.

_I assumed  the new tool I am using is not configured correctly by me_

Had myself and you down a rabbit-hole, instead of just verifying if rules applied.

👎 

Sorry again

**Comment by datacharmer** [comment]
Thanks for letting me know the outcome.
For future reference, databases installed by dbdeployer should be considered as _out-of-the-box_ as possible. The only changes applied to the configuration by dbdeployer are the ones that facilitate deployment of multiple instances in the same host. Everything else should work as expected.
A notable exception is the server UUID, which is modified by dbdeployer to be more human readable.
