### ISSUE TITLE
How to start an existing sandbox aka. server?

### ISSUE THREAD

**Issue by schorsch** [datacharmer/dbdeployer#116]
maybe i am a complete moron, but how do i start an server after a reboot. 
Me an my colleague are now searching for over an hour for the answer and have no success.

All commands are explained and have a great help, but this simple thing could not be found by us, sorry

**Comment by datacharmer** [comment]
What did you try?

Here's my take:

1.
 ```
$ dbdeployer deploy single 8.0`
$ ~/sandboxes/msb_8_0_21/status
msb_8_0_21 on
```
2. (reboot the host) `$ sudo /sbin/reboot`
3. connect again to the host
4. 
```
$ ~/sandboxes/msb_8_0_21/status
msb_8_0_21 off

$ ~/sandboxes/msb_8_0_21/start
.. sandbox server started

$ ~/sandboxes/msb_8_0_21/status
msb_8_0_21 on

$ ~/sandboxes/msb_8_0_21/use -e 'select version()'
+-----------+
| version() |
+-----------+
| 8.0.21    |
+-----------+
```

**Comment by docnewlen** [comment]
this worked like a charm, thanks for your fast response

we tried:
dbdeployer use SANDBOXNAME as described here: https://github.com/datacharmer/dbdeployer#using-the-latest-sandbox
getting the error: SANDBOXNAME not found
which came in inconsistent cause
dbdeployer sandboxes
told us the sandbox is there

**Comment by datacharmer** [comment]
Thanks for reporting this.
The "use" command was supposed to restart a stopped sandbox, but apparently I forgot to add one step. Will fix it in the next release

**Comment by schorsch** [comment]
thanks a lot and keep up this great piece of software!
