### ISSUE TITLE
Unable to set --skip-library-check using cookbook

### ISSUE THREAD

**Issue by cezmunsta** [datacharmer/dbdeployer#127]
**Describe the bug**
The flag to skip the library check is shown as part of the `cookbook create` help:
```sh
      --skip-library-check      Skip check for needed libraries (may cause nasty errors)
```
Specifying that as an argument does not generate a recipe that skips the check

**To Reproduce**
1. `dbdeployer cookbook create --flavor mysql --skip-library-check admin`
2. `grep -c skip-library-check recipes/admin-single.sh`

**Expected behavior**
A global option is expected to be applied wherever it is used, so in this scenario it is expected that the option is written to the recipe.

**Environment:**
 - OS: Ubuntu 20.04
 - 1.44

**Comment by datacharmer** [comment]
`--skip-library-check` is a global flag. As such, it applies to all sub-commands.
It is not supposed to generate anything within the cookbook recipes.
