### ISSUE TITLE
MySQL instance - Grants for new databases (or root user)

### ISSUE THREAD

**Issue by ChameleonDevil** [datacharmer/dbdeployer#130]
I have an issue with getting grants to work _for a new database on an existing sandbox_

The section in question:

Users:
> root, with the default grants as given by the server version being installed.

I have an instance installed on `port 5730 and port 5731` respectively.  (Corresponds to MySQL 5.7.30 and 5.7.31).

I can connect like this: 
````
mysql -u msandbox -p -h 127.0.0.1 -P 5730
mysql -u msandbox -p -h 127.0.0.1 -P 5731
mysql -u mycustomusername -p -h 127.0.0.1 -P 5730
````

I created a file for grants like shown in the article:

> use the option `--post-grants-sql-file` to load the instructions.
````
> cat << EOF > orchestrator.sql

CREATE DATABASE IF NOT EXISTS orchestrator;
CREATE USER orchestrator IDENTIFIED BY 'msandbox';
GRANT ALL PRIVILEGES ON orchestrator.* TO orchestrator;
GRANT SELECT ON mysql.slave_master_info TO orchestrator;

EOF

$ dbdeployer deploy single 5.7 \
  --post-grants-sql-file=$PWD/orchestrator.sql
````

This works fine for a **new empty database deployed by the SQL script (and its grants), but I now have an _existing_ instance, and want to create a new database from _within the mysql instance_**.

The article claims that `root` should be available, but:
````
mysql -u root -p -h 127.0.0.1 -P 5731
Access denied for user 'root'@'localhost' (using password: YES)
````

_I have the local instance installed on 3306, but this is not supposed to be the user I need to login with_. 

When I do this: 
````
mysql -u root -p -h localhost -P 5731
````
I am able to login, _however this seems to ignore the port (when connecting as `localhost`) because I see *different databases (those on port 3306 and not those from 5730/5731)*!

This also confirms my suspicion that port gets ignored :
````
SHOW GRANTS FOR mycustomusername;
ERROR 1141 (42000): There is no such grant defined for user 'mycustomusername' on host '%'

SHOW GLOBAL VARIABLES LIKE '%port%';
.... truncated ....
port   | 3306
````

I need to use `root@host5731` and `root@host5730`  but there does not seem a way to use root here?

I need to do one (either) of the following:

* Use `root` user at these ports,
* Get a way to let `msandbox` or `mycustomusername` to be able to have ability to do `GRANT ALL PRIVILEGES` **on a new database.**

### Why?
I cannot remove/recreate a new MySQL instance to add new databases (using the SQL file method) `--post-grants-sql-file` when I already have existing databases.

  [1]: https://github.com/datacharmer/dbdeployer/wiki/database-users

**Comment by ChameleonDevil** [comment]
After a long struggle and debug, I realized the `root user` uses the same password as `msandbox (default user)`.

For anyone else:
````
dbdeployer deploy -u root -p Somepassword
````
does not work, it will notify that `root` cannot be used, and then default to same password as `msandbox`.

[According to this issue (2018):](https://github.com/datacharmer/dbdeployer/issues/29)

**The information from that answer quoted below is a little bit misleading (and tripped me up for a while): what it should tell us is that you _cannot_ use `-u root`, but it will have the default password set as the other user you specify!**

**>  (notice that you don't need to indicate "-u root" as the root user will be assigned your given password regardless.)**

This works now: (use the password setup for the other user).
```` 
mysql -u root -p -h 127.0.0.1 -P 5732
````
Now inside the logged in mysql instance I recommend changing the password of `root` user.

> Thanks for trying dbdeployer.
> 
> dbdeployer has simplified the command structure of MySQL Sandbox. For this reasons, some of the assumptions that were valid for the old app don't hold anymore.
> 
> The easy way of running operations would be (instead of manually unpacking the tarball:)
> 
> ```
> dbdeployer unpack mysql-5.6.41-macos10.13-x86_64.tar.gz
> ```
> 
> This command will create $HOME/opt/mysql/5.6.41. You can change the destination directory using `--sandbox-binary`.
> 
> ```
> dbdeployer deploy single --port 5600 -p 'localRoot#123' 5.6.41
> ```
> 
> (notice that you don't need to indicate "-u root" as the root user will be assigned your given password regardless.)
> 
> Please read the chapter named _Standard and non-standard basedir names_ in [README](https://github.com/datacharmer/dbdeployer/blob/master/README.md).
> In short, the directory must be named "x.x.xx" or **end with** "x.x.xx" to be recognized as containing a valid version. In all other cases, you should supplement the version with `--binary-version`.
> 
> Your command would work as follows:
> 
> ```
> dbdeployer deploy single --port 5600 -p 'localRoot#123' \
>     sandbox-packages/mysql-5.6.41-macos10.13-x86_64 \
>     --binary-version=5.6.41
> ```
> 
> But I would not call this one _simple_ if compared to the recommended one.

**Comment by datacharmer** [comment]
It is not clear what you want to achieve.
In the sandbox, there is a script called `use`, which gives you access to the database without need of any options.
Instead of running the `mysql` that is in your path, you can simply run
```
$HOME/sandboxes/msb_5_7_32/use
```
or
```
$HOME/sandboxes/msb_5_7_32/use -u root
```
Moreover, if you use `mysql -u root -p -h 127.0.0.1 -P 5732`, you use the client in your $PATH, which, depending on what you have deployed, may not be fully compatible with what you have in the sandbox.

**Comment by ChameleonDevil** [comment]
> It is not clear what you want to achieve.

My apologies, I thought this was clear enough: 
> _I cannot remove/recreate a new MySQL instance to add new databases (using the SQL file method) --post-grants-sql-file when I already have existing databases._

I was trying to do the following: (syntax might be incorrect - typing this without being inside a mysql instance).  

_There are times when I want to create new databases on an existing `v.X version` sandbox_.

_I find it strange that `dbdeployer` is not used in this way to run different dbs inside the same sandbox, I assume its just that what I wanted to achieve was really unclear!_

````
CREATE USER newuser@'%' IDENTIFIED WITH mysql_native_password BY 'newpassword';
CREATE DATABASE newdatabase_notcreated_at_sandboxtime;
GRANT ALL PRIVILEGES ON newdatabase_notcreated_at_sandboxtime TO newuser@'%';
FLUSH PRIVILEGES;
````

So `msandbox` and my new user cannot `GRANT`, which I needed **root** user: `mysql -u root -p -h 127.0.0.1 -P 5731` for.

> In the sandbox, there is a script called `use`, which gives you access to the database without need of any options.
> Instead of running the `mysql` that is in your path, you can simply run
> 
> ```
> $HOME/sandboxes/msb_5_7_32/use
> ```
> 
> or
> 
> ```
> $HOME/sandboxes/msb_5_7_32/use -u root
> ```

I eventually discovered that I can use `/use -u otherusername` (I went through the documentation again). (also, see my second post), but this also let me discover the 'side-effect' of the `root` and `msandbox/user` having the same password for this instance.

I changed the `root` password after logging into the sandbox instance so that they have different logins.

> 
> Moreover, if you use `mysql -u root -p -h 127.0.0.1 -P 5732`, you use the client in your $PATH, which, depending on what you have deployed, may not be fully compatible with what you have in the sandbox.

Yes this makes total sense, at the moment I am just using different mysql versions that are close-together in versions (`5.6/5.7.30/5.7.31 etc`).  These commands are only limited to those I think are 'compatible'.  I will create aliases for the specific sandbox instance paths to ensure I don't experience issues.
