### ISSUE TITLE
500 error from binary pull

### ISSUE THREAD

**Issue by grooverdan** [datacharmer/dbdeployer#132]
**Describe the bug**

Unable to download ding gobinaries script

**To Reproduce**

curl -sf https://gobinaries.com/datacharmer/dbdeployer | PREFIX=. sh

  ==> Downloading github.com/datacharmer/dbdeployer@master
  ==> Resolved version master to v1.59.0
  ==> Downloading binary for linux amd64

  Error downloading, got 500 response from server

**Expected behavior**

Rainbows and unicorns, a 200 response would be ok too.

**Environment:**
 - x86_64 Fedora 33

**Additional context**

Has been hitting our CI on this for a while - https://buildbot.mariadb.org/#/builders/210 I was hoping it was a transient GH issue.

**Comment by datacharmer** [comment]
Hi
Thanks for reporting this issue.
The reason for the error is that [gobinaries](gobinaries.com) is still compiling with Go 1.15, while the latest version of dbdeployer requires Go 1.16.

I have no control on gobinaries, but I can offer two workarounds:

1. Use the installation script [provided by dbdeployer itself](https://github.com/datacharmer/dbdeployer/wiki/installation#installation-via-script)
```
$ curl -s https://raw.githubusercontent.com/datacharmer/dbdeployer/master/scripts/dbdeployer-install.sh | bash
dbdeployer-1.59.0.linux.tar.gz: OK
-rwxr-xr-x 1 msandbox msandbox  12M Apr 11 13:13 dbdeployer-1.59.0.linux
-rw-r--r-- 1 msandbox msandbox 5.6M Apr 16 01:52 dbdeployer-1.59.0.linux.tar.gz
-rw-r--r-- 1 msandbox msandbox   97 Apr 16 01:52 dbdeployer-1.59.0.linux.tar.gz.sha256
/home/msandbox/usr/local/bin
/home/msandbox/go/bin
/home/msandbox/bin
file dbdeployer-1.59.0.linux ready to move in $PATH
e.g.:
sudo mv dbdeployer-1.59.0.linux /usr/local/bin/dbdeployer
```
2. Pull from gobinaries, with a specific version
```
$ curl -sf https://gobinaries.com/datacharmer/dbdeployer@1.58.2 | PREFIX=. sh

  ==> Downloading github.com/datacharmer/dbdeployer@1.58.2
  ==> Resolved version 1.58.2 to v1.58.2
  ==> Downloading binary for linux amd64
  ==> Installing dbdeployer to .
  ==> Installation complete
```

**Comment by grooverdan** [comment]
Lets hope the https://github.com/tj/gobinaries/issues/36 deployment will be global for 1.16 (so intentionally name dropping an issue for good measure). I'll pick up a work around in the mean time. Thanks @datacharmer

**Comment by datacharmer** [comment]
Note that the workaround n.1 is not exactly equivalent to your previous workflow with gobinaries.

The dbdeployer script will fetch `dbdeployer-x.x.x.OS` (e.g. `dbdeployer-1.59.0.linux`), not simply `dbdeployer`.
You can automate the usage by also fetching the current version:
```
version=$(curl curl https://raw.githubusercontent.com/datacharmer/dbdeployer/master/common/VERSION)
dbdeployer=dbdeployer-${version}.linux`
```

**Comment by grooverdan** [comment]
greenness restored - https://buildbot.mariadb.org/#/builders/210/builds/349
