### ISSUE TITLE
error while filling the sandbox definition: [dbdeployer needed tools] missing executables: [hostname]

### ISSUE THREAD

**Issue by CrisDgrnu** [datacharmer/dbdeployer#139]
**Describe the bug**
When trying to deploy a sandbox i get de  following error 
```
error while filling the sandbox definition: [dbdeployer needed tools] missing executables: [hostname]
```

I have followed the installation tutorial.

**To Reproduce**
Just install dbdeployer as it is said in installation page, download and deploy a mysql tarball and try to deploy it

**Expected behavior**
The deployed datbase to work

**Environment:**
 - OS: Arch Linux x86_64
 - dbdeployer version: 1.59.0
 - tarball full name: mysql-8.0.26-linux-glibc2.17-x86_64-minimal-rebuild.tar.xz
 - tarball origin: the download command

**Comment by datacharmer** [comment]
The `hostname` command is needed to deploy sandboxes. 
If your operating system does not provide it, you can make a shell script, named `hostname`, which provides the host name of the machine where you run, same as the standard command does. Make the script executable and put it in $PATH.

For example, suppose your host name is "mymachine1":

```
echo "#!/usr/bin/env sh" > hostname
echo "echo 'mymachine1'" >> hostname

chmod +x hostname
sudo mv hostname /usr/local/bin/hostname
```

**Comment by CrisDgrnu** [comment]
Thanks!

**Comment by datacharmer** [comment]
Please close the issue if my suggestion solves it.
