### ISSUE TITLE
Option to override the default binaries path for a specific sandbox

### ISSUE THREAD

**Issue by fjssilva** [datacharmer/dbdeployer#14]
I'm missing an option that allows to override the location of the MySQL binaries when deploying a new sandbox. `mysql::sandbox` has the option `-b` that does just that.

My requirements include the possibility to have MySQL binaries in directories other than `x.x.xx` (it seems dbdeployer requires this directory naming pattern, right?). Lets say I want to compile some MySQL version using different options. In the end I'd like to save each result in directories named `5.7.22_A`, `5.7.22_B`, `5.7.22_C`, etc, and be able to create sandboxes from each one.

AFAIS, with dbdeployer, I can achieve the same if I save each compiled server in a different path using the same, normalized, version name, for example: `A/5.7.22`, `B/5.7.22`..., and then provide the binaries path using the option `--sandbox-binary=<path_to_binaries_parent>` or prefix the command with `SANDBOX_BINARY=<path_to_binaries_parent> dbdeployer ...`. Although it seems to work, it would more interesting if I could maintain all binaries folders in the same place.

Or am I missing something?

**Comment by datacharmer** [comment]
`--sandbox-binary` is the same as -b for MySQL-Sandbox.
The  x.x.x name pattern cannot be easily changed.

You can, however, use a **prefix** in the directory name.
```
$ dbdeployer versions
Basedir: $HOME/opt/mysql
5.0.86         5.0.91         5.0.96         5.1.57         5.1.63         5.1.71
5.1.73         5.5.1          5.5.37         5.5.41         5.5.44         5.5.52
5.6.21         5.6.24         5.6.26         5.6.28         5.6.29         5.6.32
5.6.33         5.6.39         5.6.40         5.7.10         5.7.11         5.7.12
5.7.13         5.7.14         5.7.15         5.7.16         5.7.17         5.7.18
5.7.19         5.7.20         5.7.21         5.7.22         5.7.5          5.7.6
5.7.7          5.7.8          5.7.9          8.0.0          8.0.1          8.0.11
8.0.2          8.0.3          8.0.4          full_5.6.26    full_5.6.32    full_5.7.10
full_5.7.11    full_5.7.12    full_5.7.13    full_5.7.14    full_5.7.15    full_5.7.16
full_5.7.17    full_5.7.19    full_5.7.21    full_5.7.9     full_8.0.0     full_8.0.1
full_8.0.3     full_8.0.4     full_ps5.7.10  ma10.0.17      ma10.0.20      ma10.1.13
ma10.1.5       ma10.1.6       ma10.1.7       ma10.1.8       ma5.5.40       ms5.7.2
new5.7.21      ps5.5.43       ps5.7.10

$ dbdeployer deploy single full_8.0.3
Database installed in $HOME/sandboxes/msb_full_8_0_3
run 'dbdeployer usage single' for basic instructions'
. sandbox server started
```

**Comment by fjssilva** [comment]
Well, there's a difference between dbdeployer's `--sandbox-binary` and mysql::sandbox's `-s`, while the first points to to parent directory, the latter points directly to the mysql directory, allowing to skip the version pattern.

Using prefixes works too. It just adds to confusion in the binaries directory listing. I'd say that it helps having the binaries grouped by version.

Actually, to me, it would be enough if suffixes were allowed as well. I don't require any change regarding the x.x.x pattern.

**Comment by datacharmer** [comment]
After looking at the possible solutions, I saw that in fact adding an option `--binary-version` would solve your problem (allows suffixes and completely non-version related names) with the minimum code disruption.
I will release after the tests are completed, together with the fix for Issue #10.

**Comment by fjssilva** [comment]
Thank you.

**Comment by datacharmer** [comment]
Taken action in release 1.5.0. Excerpt from README.md:


dbdeployer expects to get the binaries from ``$HOME/opt/mysql/x.x.xx``. For example, when you run the command ``dbdeployer deploy single 8.0.11``, you must have the binaries for MySQL 8.0.11 expanded into a directory named ``$HOME/opt/mysql/8.0.11``.

If you want to keep several directories with the same version, you can differentiate them using a **prefix**:

    $HOME/opt/mysql/
                8.0.11
                lab_8.0.11
                ps_8.0.11
                myown_8.0.11

In the above cases, running ``dbdeployer deploy single lab_8.0.11`` will do what you expect, i.e. dbdeployer will use the binaries in ``lab_8.0.11`` and recognize ``8.0.11`` as the version for the database.

When the extracted tarball directory name that you want to use doesn't contain the version number (such as ``/home/dbuser/build/path/5.7-extra``) you need to provide the version using the option ``--binary-version``. For example:

    dbdeployer deploy single 5.7-extra \
        --sandbox-binary=/home/dbuser/build/path \
        --binary-version=5.7.22

In the above command, ``--sandbox-binary`` indicates where to search for the binaries, ``5.7-extra`` is where the binaries are, and ``--binary-version`` indicates which version should be used.
