### ISSUE TITLE
Add downloads for 8.0.23 for macOS (arm64 and x64)

### ISSUE THREAD

**Issue by jpike88** [datacharmer/dbdeployer#144]
Aurora has recently announced support of mysql 8, but their first and only version is specifically 8.0.23. Probably a good idea to list that version for all platforms

**Comment by datacharmer** [comment]
Thanks for the suggestion.
I added downloads for 8.0.23 in [version 1.64.0](https://github.com/datacharmer/dbdeployer/releases/tag/v1.64.0).
It's x64 only, as you can see in the downloads page.
<img width="1408" alt="Screenshot 2021-11-27 at 12 57 31" src="https://user-images.githubusercontent.com/347371/143680346-9c7e53b6-d6ff-4a47-a188-ee88c39883b7.png">

**Comment by jpike88** [comment]
<img width="894" alt="Screen Shot 2022-01-14 at 14 25 40" src="https://user-images.githubusercontent.com/9585787/149467972-d0533c09-b8ba-43d3-8e9e-84befe61cc8b.png">
looks like they've updated the UI. I opened a fresh issue about arm64
