### ISSUE TITLE
arm64 downloads

### ISSUE THREAD

**Issue by jpike88** [datacharmer/dbdeployer#145]
add some downloads for arm64, for M1 Macs. looks like just 8.0.27 but that's a good start

**Comment by jpike88** [comment]
makes sense to define a new OS: "DarwinARM64"

**Comment by datacharmer** [comment]
I have a couple of problems with this task at the moment:

1. I don't own an M1 Mac. I can't just add the downloads for the new architecture, as it would require an update in the code, and I would also need to test the new downloads.
2. Even if I find someone who would let me access an M1 remotely, I am unable to code now and I will be for several weeks, as an accident has deprived me of the use of my dominant hand.

That said, if someone would submit a pull request with the code changes and the downloads, I can have a look.

**Comment by jpike88** [comment]
No problem I could have a crack. Just a question regarding how you want to differentiate apple from intel chips in the list.json?

**Comment by datacharmer** [comment]
That depends on how an M1 defines itself. The operating system used in the tarball list must be detectable by the function `CheckTarballOperatingSystem` (in `common/checks.go`). As you can see from that function, figuring out the right type requires some experimentation. Probably it would be necessary replacing every occurrence of `runtime.GOOS` into a function that combines OS and architecture.

**Comment by jpike88** [comment]
that looks about right. I ran locally and got these values:

runtime.GOARCH => arm64
runtime.GOOS => darwin

**Comment by datacharmer** [comment]
I have opened a new branch that should fix this issue. (https://github.com/datacharmer/dbdeployer/tree/arm-64-downloads)
It would be nice if someone with access to a `arm64` architecture would compile this branch and test the `downloads` commands: `get-by-version`, `add`, `add-remote`, `list`, `tree`

**Comment by datacharmer** [comment]
[Release v1.69.0](https://github.com/datacharmer/dbdeployer/releases/tag/v1.69.0) resolves this issue
