### ISSUE TITLE
sysbench_ready run does not use env variable

### ISSUE THREAD

**Issue by utdrmac** [datacharmer/dbdeployer#147]
**Describe the bug**
The ./sysbench_ready script allows for 'prepare' and 'run'.  The 'prepare' option will accept a custom $SB_DATABASE env but 'run' is hard-coded to 'sbtest'

**To Reproduce**
1. Run `$ SB_DATABASE=sysbench ./sysbench_ready prepare` to create the custom database and create tables with data
2. Run `$SB_DATABASE=sysbench ./sysbench_ready run` and observe failure.

**Expected behavior**
For prepare and run to function the same

https://github.com/datacharmer/dbdeployer/blob/35399d264b525e7254c5038728bbe183ac97f213/sandbox/templates/single/sysbench_ready.gotxt#L5

https://github.com/datacharmer/dbdeployer/blob/35399d264b525e7254c5038728bbe183ac97f213/sandbox/templates/single/sysbench_ready.gotxt#L46

https://github.com/datacharmer/dbdeployer/blob/35399d264b525e7254c5038728bbe183ac97f213/sandbox/templates/single/sysbench_ready.gotxt#L62

**Comment by datacharmer** [comment]
Thanks for reporting this issue. Fixed in release v1.65.1
