### ISSUE TITLE
"./my" prefix script adds "my" in front of the tool name

### ISSUE THREAD

**Issue by pmitev** [datacharmer/dbdeployer#153]
**Describe the bug**
"./my" prefix script adds "my" in front of the tool name i.e. 
```
./my mqsldump
/home/user/opt/mysql/8.0.30/bin/mymqsldump not found
```

**To Reproduce**
1. 
```
dbdeployer deploy single 8.0
# 8.0 => 8.0.30
Database installed in $HOME/sandboxes/msb_8_0_30
run 'dbdeployer usage single' for basic instructions'
....... sandbox server started
```
2.
``` bash
cd $HOME/sandboxes/msb_8_0_30
```
3. The error
```bash
./my mqsldump
/home/user/opt/mysql/8.0.30/bin/mymqsldump not found
```

**Expected behavior**
It is supposed  to invoke any command named "my*" from the MySQL /bin directory.

**Environment:**
 - OS: [ Ubuntu 22.04]
 - dbdeployer version 1.69.1

**Additional context**
https://github.com/datacharmer/dbdeployer/blob/35399d264b525e7254c5038728bbe183ac97f213/sandbox/templates/single/my.gotxt#L18 

changing the line from:
`MYSQLCMD="$CLIENT_BASEDIR/bin/my$SUFFIX"`
to
`MYSQLCMD="$CLIENT_BASEDIR/bin/$SUFFIX"`

fixes the problem for me.

**Comment by pmitev** [comment]
I see. This is unfortunate since I wanted originally to run mariabackup and the fix above seems to work as I intended ;-)

```bash
$ /home/user/opt/mysql/10.9.2/bin/mariabackup | grep "^datadir"
/home/user/opt/mysql/10.9.2/bin/mariabackup based on MariaDB server 10.9.2-MariaDB linux-systemd (x86_64)
datadir                           /var/lib/mysql

$ ./my mariabackup | grep "^datadir"
/home/user/opt/mysql/10.9.2/bin/mariabackup based on MariaDB server 10.9.2-MariaDB linux-systemd (x86_64)
datadir                           /home/user/sandboxes/msb_10_9_2/data
```

**Comment by datacharmer** [comment]
Doing the change as you request would break compatibility for all the users who rely on this capability.
You can, however, customize your own copy of dbdeployer by editing the "my" template.
See points 4 and 5 of [sandbox customization](https://github.com/datacharmer/dbdeployer/wiki/sandbox-customization)

**Comment by pmitev** [comment]
I agree. For now, I think, I will instead create a soft link `ln -s mariabackup mymariabackup`. It looks like less intrusive "fix" for my problem.
```bash
$ ./my mariabackup | grep "^datadir"
/home/user/opt/mysql/10.9.2/bin/mymariabackup based on MariaDB server 10.9.2-MariaDB linux-systemd (x86_64)
datadir                           /home/user/sandboxes/msb_10_9_2/data
```
Thanks again!
