### ISSUE TITLE
1.69.2 isn't in releases, but the dbdeployer-install.sh wants it to be.

### ISSUE THREAD

**Issue by grooverdan** [datacharmer/dbdeployer#154]
**Describe the bug**

f9d93248c45af9ab882885ea0614b609aac6f324 adds 1.69.2 to common/VERSION. This file is used by the dbdeployer-install.sh is but without the releases file it files to install.
 
```
+ curl -s https://raw.githubusercontent.com/datacharmer/dbdeployer/master/scripts/dbdeployer-install.sh | bash
shasum: dbdeployer-1.69.2.linux.tar.gz.sha256: no properly formatted SHA checksum lines found
```

Linux:

ref: https://buildbot.mariadb.org/#/builders/210/builds/3232/steps/2/logs/stdio

**Comment by datacharmer** [comment]
Thanks for filing this issue.
The good news is that there is no bug. The poor shell script was doing exactly what its human overlord instructed it to do, i.e. looking for a release according to the `VERSION` file contents.
The error came from the human, who after the tests had cleared the Github actions, forgot to upload the binaries.
Apologies for the inconvenience.
Now there is a release 1.69.2, and the installation script can resume its task without being blamed for my shortcomings.

**Comment by grooverdan** [comment]
Thanks @datacharmer, dbdeployer overlord and very human :smile:.

All good now - https://buildbot.mariadb.org/#/builders/210/builds/3264
