### ISSUE TITLE
how to upgrade dbdeployer <1.36

### ISSUE THREAD

**Issue by WilliamAnthony** [datacharmer/dbdeployer#155]
my current dbdeployer is 1.34 and I want to upgrade it to the latest version.

I tried start the sandboxes with the latest dbdeployer (1.69.2), 
The message : One or more empty values found in defaults. Defaults file /home/william/.dbdeployer/config.json not validated. Loading internal defaults.

Tried download 1.36 then execute "dbdeployer update". Same message displayed.

Thanks.

**Comment by datacharmer** [comment]
Hi
Please remove the file `/home/william/.dbdeployer/config.json`, and the message will go away

**Comment by WilliamAnthony** [comment]
Hi, it's worked. Thanks.
