### ISSUE TITLE
Sandbox start script gives an error message if the current working directory path has spaces in it.

### ISSUE THREAD

**Issue by johan718** [datacharmer/dbdeployer#156]
**Describe the bug**
If your current working directory path has spaces in it, the start script throws an error:

path/to/start: line 57: cd: /path/that/has/spaces : No such file or directory

**To Reproduce**
1. change directory into a path with spaces in it, such as /Users/datacharmer/mysql test directory/.
2. run sandbox start script ./start

**Expected behavior**
. sandbox server started

**Environment:**
 - OS: macOS 12.6
 - dbdeployer version: 1.69.1

**Additional context**
Line 57 in the start script should be changed from `cd $CURDIR` to `cd "$CURDIR"`.

**Comment by datacharmer** [comment]
Thanks for filing this issue.
I confirm the problem, and I will make a new release once the tests are done.

**Comment by johan718** [comment]
Thanks for the info.

**Comment by datacharmer** [comment]
Fixed in [release 1.69.3](https://github.com/datacharmer/dbdeployer/releases/tag/v1.69.3)
