### ISSUE TITLE
unknown option '--initialize-insecure'

### ISSUE THREAD

**Issue by WilliamAnthony** [datacharmer/dbdeployer#159]
**Describe the bug**
when deploy latest mariadb version 10.10.2, I got error: unknown option '--initialize-insecure'

**To Reproduce**
1. Run the command 'dbdeployer deploy single 10.10.2'
2. See error 
2023-01-13 16:27:18 0 [ERROR] Could not open mysql.plugin table: "Table 'mysql.plugin' doesn't exist". Some plugins may be not loaded
2023-01-13 16:27:18 0 [ERROR] /home/william/opt/mysql/mdb10.10.2/bin/mysqld: unknown option '--initialize-insecure'
2023-01-13 16:27:18 0 [ERROR] Aborting

**Environment:**
 - OS: Ubuntu 22.04
 - dbdeployer version 1.69.2
 - mariadb-10.10.2-linux-systemd-x86_64.tar.gz

**Comment by datacharmer** [comment]
How did you unpack the binary? 
It seems that dbdeployer has been led to believe that you are using a regular MySQL binary.

Here's what I did:
```
$ wget https://dlm.mariadb.com/2690820/MariaDB/mariadb-10.10.2/bintar-linux-systemd-x86_64/mariadb-10.10.2-linux-systemd-x86_64.tar.gz

$ dbdeployer unpack mariadb-10.10.2-linux-systemd-x86_64.tar.gz
Unpacking tarball mariadb-10.10.2-linux-systemd-x86_64.tar.gz to $HOME/opt/mysql/10.10.2
.........100.........200.........300.........400.........500.........600.........700.........800.........
[...]
........20000.........20100.........20200.........20300.........20400.20415
Renaming directory $HOME/opt/mysql/mariadb-10.10.2-linux-systemd-x86_64 to $HOME/opt/mysql/10.10.2

$ cat ~/opt/mysql/10.10.2/FLAVOR
mariadb

$ dbdeployer deploy single 10.10
# 10.10 => 10.10.2
Database installed in $HOME/sandboxes/msb_10_10_2
run 'dbdeployer usage single' for basic instructions'
. sandbox server started
```

If you unpacked the binary manually, add a file named './10.10.2/FLAVOR' containing the word `mariadb` and repeat the installation. You may need to remove the failed installation manually.
For example:
```
$ rm -rf ~/sandboxes/msb_10_10_2/
$ echo -n mariadb > ~/opt/mysql/10.10.2/FLAVOR
$ dbdeployer deploy single 10.10
```

**Comment by WilliamAnthony** [comment]
Yes, it works.
But I didn't do this FLAVOR thing on my mariadb 10.1 sandboxes.
Anyway thanks.
