### ISSUE TITLE
MySQL 8.0.33 Added

### ISSUE THREAD

**Issue by iroddis** [datacharmer/dbdeployer#164]
Could you please add MySQL 8.0.33 support? It was released on 2023-04-18 (according to the [release notes](https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-33.html)).

**Comment by httpete** [comment]
bump on this - It has been a while since this was released and we rely on it downstream.

**Comment by datacharmer** [comment]
Fixed in [release 1.73.0](https://github.com/datacharmer/dbdeployer/releases/tag/v1.73.0)
