### ISSUE TITLE
update does not update config file

### ISSUE THREAD

**Issue by utdrmac** [datacharmer/dbdeployer#166]
**Describe the bug**
The feature `dbdeployer update` does not update the config file. After updating the binary, every subsequent command displays an annoying message about version mismatch.

**Expected behavior**
I expect both binary and config file to be upgraded.

**Environment:**
 - Ubuntu 18 LTS
 - dbdeployer 1.62.0 -> 1.70.0

```
$ dbdeployer update
......  7.0 MB
1
  97 B
checksum for dbdeployer-1.72.0.linux.tar.gz matches
dbdeployer version 1.72.0

$ dbdeployer versions
`Provided defaults are for version 1.62.0. Current version is 1.70.0
`********************************************************************************
`Defaults file /home/xxxx/.dbdeployer/config.json not validated.
`Loading internal defaults
`********************************************************************************
`
`Provided defaults are for version 1.62.0. Current version is 1.70.0
Basedir: /home/drmac/dbdeployer/opt/mysql
5.7.38     8.0.32     pxc8.0.27
```

The lines above prefixed with ` (added by me) are printed for every command issued. Why didn't the config file get updated to match the new version?

**Comment by utdrmac** [comment]
> The config file cannot be updated.

Of course it can. os.Open(), f.Read(), parse, upgrade object, f.Write(), f.Close(). Much like a `git merge`, you have the user's previous config, and you have the new config with defaults. Merge them. Write it out. config upgraded.

> As a workaround, 

I must use a "workaround" every time I upgrade dbdeployer?

> try applying the config changes to the new dbdeployer

What config changes? I haven't made any changes to the config.

Here's what happened:
1. Download dbdeployer
2. Play with a few commands. Neat tool.
3. Realize you don't have latest version.
4. Upgrade using built-in function
5. Can't use new version without constant warnings about version config

As end-user, I'm expected to manually migrate the config file every time I upgrade?

**Comment by datacharmer** [comment]
> Of course it can.
What I mean is that the way dbdeployer is designed, it privileges user choices (customised configuration) and prevents bad usage by means of nasty messages.

> I haven't made any changes to the config.

Then simply delete it. Apparently, you don't need a customised config. But dbdeployer will prevent a mixup **by design**.
If you don't have a customised config, all updates will work silently.
