### ISSUE TITLE
Tests are failing after merge

### ISSUE THREAD

**Issue by httpete** [datacharmer/dbdeployer#168]
Hi @datacharmer , the build is failing after the merge I did.

**Comment by datacharmer** [comment]
I know. It has nothing to do with the changes you provided.
The reason is that the server used for the tests has changed, and some of the tests fail for incompatibility.
I need to rework the test suite to be less dependent from the environment, but it is not a quick task.

**Comment by httpete** [comment]
Thanks @datacharmer but did you see my comment about the --minimal mysql? I followed the exact steps you told me to:

https://github.com/datacharmer/dbdeployer/issues/165#issuecomment-1611706472

But the end result is I don't have a mysql 8.0.33 minimal=false entry.

**Comment by datacharmer** [comment]
Well, I saw it after I merged the PR. :(
The example was unfortunate, as it should have been without the `--minimal`. That way, dbdeployer collects all available tarballs.

**Comment by httpete** [comment]
Can you fix it @datacharmer  ? I feel badly for all the downstream consumers that might want that. This project is used by asdf, which is not a small thing. From now on I will know how to update it with the proper commands.

**Comment by datacharmer** [comment]
I will, but my day job takes precedence.

**Comment by datacharmer** [comment]
Fixed in [release 1.73.0](https://github.com/datacharmer/dbdeployer/releases/tag/v1.73.0)
