### ISSUE TITLE
Unable to upgrade sandbox MariaDB 10.3.22 to 10.11.X via dbdeployer 

### ISSUE THREAD

**Issue by jwnmohan** [datacharmer/dbdeployer#170]
Unable to upgrade sandbox MariaDB 10.3.22 to 10.11.X via dbdeployer 

I am new to dbdeployer and i have a server running 2 DB's Mysql and mariaDB via dbdeployer and i am planning to upgrade only MariaDB from 10.3.22 to 10.11.0  . 

I have deployed my both the MariaDB's as single as mentioned in the upgrade steps 

I have followed the steps from "https://github.com/datacharmer/dbdeployer/wiki/sandbox-upgrade" , But i am unable to upgrade my MariaDB , I am unable to find mysql_upgrade command under my Sandbox directories , So i went in to the tar ball  extracted extracted path and i ran ./mysql_upgrade and i got the below error 

Version check failed. Got the following error when calling the 'mysql' command line client
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)

Please advise or suggest what wrong i am doing here or how to proceed with this upgrade 

**Environment:**
 - OS: Centos 7
 - dbdeployer version : 1.65.0
 - tarball full name "mariadb-10.3.28-linux-systemd-x86_64.tar.gz" ==> "mariadb-10.11.0-linux-systemd-x86_64.tar.gz
 - tarball origin (from where it was downloaded)  ==> MariaDB downloads 

**Hardware: (if applicable)**
 - root -- 300GB
 - Total RAM -- 16GB

**Additional context**

**Comment by datacharmer** [comment]
This functionality is only supported for MySQL, not MariaDb
