### ISSUE TITLE
Port management glitch

### ISSUE THREAD

**Issue by fjssilva** [datacharmer/dbdeployer#26]
It seems that when installing two consecutive versions of the same MySQL series, from higher to lower, the ports are not chosen correctly.

1. Deploy MySQL 5.7.22 with default port. It runs at 5722.
2. Deploy MySQL 5.7.21 with default port. It runs at 5723, but 5721 is available.

I also tried deploying the second server with the option --port 5721 but with no luck, it was overridden with 5723.

To work around  this I had to move the "conflicting" sandbox msb_5_7_22 out of the sandboxes directory, then deploy 5.7.21 with defaults again (now runs at 5721) and finally move the other sandbox back.

I'm using dbdeployer version 1.8.0, on Linux.

**Comment by datacharmer** [comment]
Thanks for reporting this issue.
It is indeed a bug. I could reproduce it as described. 
I need to investigate it.

The ports are selected correctly when the deployment happens in the opposite order (5.7.21 first and 5.7.22 later.)

Moreover, the bad behavior happens only when the two revision numbers are contiguous.  If I deploy 
5.7.22 and then 5.7.20, the ports are created as expected.

**Comment by datacharmer** [comment]
Fixed in version 1.8.3
