### ISSUE TITLE
undocumented go deps when building with MKDOCS=1 and build should fail properly

### ISSUE THREAD

**Issue by JoKoT3** [datacharmer/dbdeployer#27]
**Describe the bug**
MKDOCS=1 build.sh linux 1.8.0 fail because of unmet dependencies

**To Reproduce**
1. Not having the following dependencies in your GOPATH
github.com/cpuguy83/go-md2man/md2man
gopkg.in/yaml.v2
2. Run the command 'MKDOCS=1 build.sh linux 1.8.0'
3. See error: 
```
+ env GOOS=linux GOARCH=386 go build --tags docs -o dbdeployer-1.8.0-docs.linux .
../../spf13/cobra/doc/man_docs.go:26:2: cannot find package "github.com/cpuguy83/go-md2man/md2man" in any of:
	/usr/lib/go/src/github.com/cpuguy83/go-md2man/md2man (from $GOROOT)
	/home/john/go/src/github.com/cpuguy83/go-md2man/md2man (from $GOPATH)
tar: dbdeployer-1.8.0-docs.linux: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors

```

```
+ env GOOS=linux GOARCH=386 go build --tags docs -o dbdeployer-1.8.0-docs.linux .
../../spf13/cobra/doc/yaml_docs.go:26:2: cannot find package "gopkg.in/yaml.v2" in any of:
	/usr/lib/go/src/gopkg.in/yaml.v2 (from $GOROOT)
	/home/john/go/src/gopkg.in/yaml.v2 (from $GOPATH)
```

**Expected behavior**
1. docs should state 
github.com/cpuguy83/go-md2man/md2man
and
gopkg.in/yaml.v2
Although they seems to be dependencies of the cobra lib, and not dbdeployer

2. build should properly fail

**Environment:**
 - OS: Arch Linux
 - dbdeployer version 1.8.0
 - tarball full name: NA
 - tarball origin: NA

**Additional context**
My GO SRC only contained: 
spf13/cobra
jteeuwen/go-bindata
datacharmer/dbdeployer
before trying to build

**Comment by datacharmer** [comment]
Thanks for reporting this issue. 
The build script should add the docs package when compiling with MKDOCS. 
I will fix it when I am back from travel.

**Comment by datacharmer** [comment]
Fixed in latest commit.
Now, when building with MKDOCS and spf13/cobra/docs was not in path, an appropriate message suggests which 'go get' command would solve the problem. No build is attempted before the dependencies are correct.
