### ISSUE TITLE
the difference from MySQL_sandbox?

### ISSUE THREAD

**Issue by dikang123** [datacharmer/dbdeployer#3]
I was wondering the difference between MySQL_sandbox and this tool.

**Comment by lefred** [comment]
written in Go ? ;-)

**Comment by datacharmer** [comment]
The difference is that this package is written with the goal of not having dependencies. This, it has been rewritten from the ground up in Go, and it implements the main features of MySQL-Sandbox.
There is already something that dbdeployer can do and MySQL-Sandbox can't: group replication without extenal scripts.
MySQL-Sandbox will be maintained until dbdeployer can do everything MySQL-Sandbox does, but the plan is for MySQL-Sandbox to be abandoned and new features to be added only in dbdeployer.
