### ISSUE TITLE
Having the possibility to use different instance of the same environment

### ISSUE THREAD

**Issue by lefred** [datacharmer/dbdeployer#4]
If I would like to have for example two different setup of a MySQL Group Replication for the same version is not possible:

```
$ dbdeployer-0.1.11.linux --topology=group replication 8.0.4
Directory /home/fred/sandboxes/group_msb_8_0_4 already exists
```
It would be great to be able to do this. (or maybe I didn't find the right option to achieve this)

Thank you for such useful tool :)

**Comment by datacharmer** [comment]
Release 0.1.13 fixes this issue.

    $ dbdeployer replicatioon 8.0.4
    $ dbdeployer sandboxes
    rsandbox_8_0_4       : master-slave              8.0.4 [18405 18406 18407]

    $ dbdeployer replication 8.0.4 --sandbox-directory=rsandbox2_8_0_4 --base-port=18600
    $ dbdeployer sandboxes
    rsandbox2_8_0_4      : master-slave              8.0.4 [18601 18602 18603]
    rsandbox_8_0_4       : master-slave              8.0.4 [18405 18406 18407]
