### ISSUE TITLE
Add support for --client-from=X

### ISSUE THREAD

**Issue by morgo** [datacharmer/dbdeployer#49]
**Is your feature request related to a problem? Please describe.**

I am working on adding TiDB support to dbdeployer.  One of the differences that it has from regular MySQL packages, is that it ships without clients (so the dbdeployer `use` command for example will fail).

I could work around this by requiring a `mysql` to be configured in the `$PATH`, but in discussion at FOSDEM @datacharmer suggested there is a use case in MySQL for *both* Docker and using a newer client against an older server and vice-versa.

**Describe the solution you'd like**

```
dbdeployer deploy single 8.0.14 --client-from=5.7.23
```

**Describe alternatives you've considered**

The alternative is to require `MYSQL_EDITOR` to be specified, or require a global `mysql` in `$PATH`.

**Additional context**

**Comment by datacharmer** [comment]
Notes for implementation:

In addition to creating two `BASEDIR` variables in the scripts (I am thinking of `BASEDIR` for the server stuff and `BASEDIR_CLIENT` for the client calls) we also need to either duplicate `LD_LIBRARY_PATH` or use different values for the libraries depending on which script we are working in.

**Comment by datacharmer** [comment]
implemented in `capabilities` branch
