### ISSUE TITLE
Change evaluation of version to include a flavor

### ISSUE THREAD

**Issue by datacharmer** [datacharmer/dbdeployer#50]
**Problem.**
The database server capabilities (such as GTID, semi-synch, MySQLX) are now evaluated only by comparing the server version with the minimal version where the feature was enabled.

This method works well if we limit ourselves to MySQL server, but will fail if we start adding other flavors, such as NBD server, Percona Server + PXC, or MariaDB with or without Galera.
The method will also fail when we try to add non-MySQL forks such as TiDB.

**What can we do**
Instead of simply comparing the version, which becomes quickly untenable, we can use a method made of the flavor (e.g. "mysql", "mariadb", "ndb", tidb", and so on) and a version.

cc @morgo

**Comment by morgo** [comment]
LGTM

**Comment by datacharmer** [comment]
implemented in `capabilities` branch
