### ISSUE TITLE
unpack command should create a FLAVOR file for the extracted tarball

### ISSUE THREAD

**Issue by datacharmer** [datacharmer/dbdeployer#52]
**problem**
We want to be able to detect which flavor a given tarball is (MySQL, Percona Server, NDB, etc)

**Describe the solution you'd like**
To facilitate the task, we could tell the `unpack` command to create a FLAVOR file when extracting from the tarball, indicating what flavor we are dealing with.

cc @morgo

**Comment by morgo** [comment]
LGTM.  The only confusing aspect might be for MariaDB, where from 10.1 Galera stops being a flavor, but is supported.  Users might not relate to this being called `mariadb+galera` as the flavor, but see it as a capability.

**Comment by datacharmer** [comment]
Implemented in `capabilities` branch
