### ISSUE TITLE
Define criteria to detect the flavor of a tarball contents

### ISSUE THREAD

**Issue by datacharmer** [datacharmer/dbdeployer#53]
We need some criteria that would help us identify which flavor of database server we are dealing with.

Possible values are:

* mysql
* percona server
* percona server with PXC
* ndb cluster
* mariadb
* mariadb with Galera
* tidb

There are three methods to detect the flavor:

1. Using an explicit option during the deployment (`--flavor=X`)
2. Using a FLAVOR file inside the extracted tarball (Issue #52)
3. Evaluating the files in the tarball to decide what we are dealing with.

The difficult part is item n. 3, because sometimes the difference between flavors is not easily detectable.

Related to Issues #50 and #52.

cc @morgo

**Comment by morgo** [comment]
Some notes:
* All releases of MariaDB from 10.1 are of variant "mariadb with Galera"  ([source](https://mariadb.com/kb/en/library/what-is-mariadb-galera-cluster/))
* For Percona, there are two flavors still.
* For TiDB, I would just check for `./bin/tidb-server`

I downloaded `Percona-XtraDB-Cluster-5.7.24-rel26-31.33.1.Linux.x86_64.ssl102.tar.gz` from Percona, and there are quite a few files that can be used for detection:

* `./bin/garbd` (the galera arbitrator)
* `./bin/clustercheck` (used for galera+HAProxy etc)
* `./bin/wsrep_sst_*` (used for provisioning)

I verified these are not in the 8.0 package.  As another side-node, I don't think TokuDB is a capability in percona server when Galera is.

For MySQL Cluster, I downloaded `mysql-cluster-gpl-7.6.9-linux-glibc2.12-x86_64.tar.gz` and saw that there are a lot of files in `./bin`, for example `./bin/ndbd`, `./bin/ndb_mgm`, `./bin/ndb_mgmd`.

**Comment by datacharmer** [comment]
Implemented in versions 1.20.0 and 1.21.0
