### ISSUE TITLE
dbdeployer versions looks for 'mysqld' executable

### ISSUE THREAD

**Issue by morgo** [datacharmer/dbdeployer#56]
**Is your feature request related to a problem? Please describe.**

Currently `dbdeployer versions` will only list unpacked tarballs that have a file in the path `./bin/mysqld`.  This is safe for MariaDB/Percona/MySQL, but not TiDB.

**Describe the solution you'd like**

It would be nice to have a wider list that included:
```
mysqld-debug
mysqld
tidb-server
```
I don't think any packages exist that ship a debug-build without a regular, but it might be nice to be more inclusive.

**Describe alternatives you've considered**

An alternative might be that this can probe flavors to find a list of binary names, but I am not sure if the complexity is warranted given TiDB is the only outlier. 

**Additional context**

If I manually touch a file in `./bin/mysqld` it shows in the list, so I can confirm that it is this and not another issue.

**Comment by datacharmer** [comment]
Fixed in `capabilities` branch
