### ISSUE TITLE
dbdeployer deploy single hangs

### ISSUE THREAD

**Issue by morgo** [datacharmer/dbdeployer#57]
**Describe the bug**

Running `dbdeployer deploy single 3.0.0` hangs when using TiDB. 

**To Reproduce**
Steps to reproduce the behavior (on Linux):
```
wget http://download.pingcap.org/tidb-latest-linux-amd64.tar.gz
dbdeployer unpack tidb-latest-linux-amd64.tar.gz --unpack-version=3.0.0
git clone git@github.com:morgo/dbdeployer-tidb-template.git
dbdeployer defaults template import single dbdeployer-tidb-template/new-templates/
dbdeployer deploy single 3.0.0 
```

Notes:
- It doesn't hang if I add `--skip-start`, and then manually starting works fine.
- It is not related to `load_grants_template` as I suspected.  I set that to `exit 0` at the start of the script to no effect.
- Adding `--client-from` has no effect.

**Expected behavior**

Not hang

**Environment:**
 - `Linux ryzen 4.18.0-15-generic #16-Ubuntu SMP Thu Feb 7 10:56:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
 - dbdeployer version: `https://github.com/datacharmer/dbdeployer/tree/capabilities` (up to date)

Also reproduced on Debian Linux container (my laptop)

**Hardware: (if applicable)**
```
morgo@ryzen:~/go/src/github.com/morgo/dbdeployer-tidb-template$ df -h .
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda3       166G   77G   81G  49% /
morgo@ryzen:~/go/src/github.com/morgo/dbdeployer-tidb-template$ free -g
              total        used        free      shared  buff/cache   available
Mem:             62           7          47           0           7          54
Swap:             0           0           0
```
**Additional context**

**Comment by datacharmer** [comment]
Please change the start template as follows:
```
$ cat dbdeployer-tidb-template/new-templates/single/start_template
#!/bin/bash
{{.Copyright}}
# Generated by dbdeployer {{.AppVersion}} using {{.TemplateName}} on {{.DateTime}}
source {{.SandboxDir}}/sb_include

$BASEDIR/bin/tidb-server -config $SBDIR/tidb.toml > $SBDIR/tidb.log 2>&1 &
exit 0
```
Then deploy again using `--client-from=5.7.25`

**Comment by morgo** [comment]
It fixed it.  Thank you!
