### ISSUE TITLE
Add build files to .gitignore

### ISSUE THREAD

**Issue by morgo** [datacharmer/dbdeployer#58]
**Is your feature request related to a problem? Please describe.**

May I suggest adding build artifacts to `.gitignore`?  This will prevent them from being accidentally committed by a contributor.

**Describe the solution you'd like**

```
diff --git a/.gitignore b/.gitignore
index 786de81..31f5865 100644
--- a/.gitignore
+++ b/.gitignore
@@ -1,3 +1,12 @@
 *~
 .idea/
-
+dbdeployer-*-docs.linux
+dbdeployer-*-docs.linux.tar.gz
+dbdeployer-*-docs.osx
+dbdeployer-*-docs.osx.tar.gz
+dbdeployer-*.linux
+dbdeployer-*.linux.tar.gz
+dbdeployer-*.osx
+dbdeployer-*.tar.gz
+test/sort_versions.Darwin
+test/sort_versions.linux
```

**Describe alternatives you've considered**

N/A

**Comment by datacharmer** [comment]
I usually do this in `.git/info/exclude`, but making the rules available to contributors won't hurt.
Added in `capabilities` branch
