### ISSUE TITLE
Add flavors to sandboxes list

### ISSUE THREAD

**Issue by datacharmer** [datacharmer/dbdeployer#63]
**Is your feature request related to a problem? Please describe.**
We need the flavor of the database (mysql, tidb, percona server, etc) when we list the installed sandboxes.

**Describe the solution you'd like**
Given that we can't change the default output, as it would break compatibility, we need to add an option. For example:
```
$ dbdeployer sandboxes --catalog --flavor --header
flavor          name                      version    type                 nodes ports
------          ----                      -------    -----                ----- -----
mysql           msb_5_0_96                5.0.96     single                   0 [5096 ]
tidb            msb_tidb3_0_0             tidb3.0.0  single                   0 [3000 ]
```

**Describe alternatives you've considered**
a. A new command with more detail than the current `dbdeployer sandboxes`
b. Instead of an option to include the flavor, a new format (json, yaml) that shows the enhanced detail.

**Additional context**
Whatever solution we choose, it will probably require a refactoring of `cmd/sandboxes.go`, as it has become difficult to maintain.

cc: @morgo

**Comment by morgo** [comment]
> Given that we can't change the default output, as it would break compatibility, we need to add an option.

`--flavor` looks like a good default display option, so it's regrettable it breaks backwards compatibility.  I do like the idea of (b) for programs, so there will be flexibility to break the interactive format.

**Comment by datacharmer** [comment]
Added in version 1.21.0
```
$ dbdeployer sandboxes --flavor --header
            name                  type       version          ports           flavor
---------------------------- -------------- --------- ---------------------- --------
 all_masters_msb_5_7_23   :   all-masters    5.7.23    [21224 21225 21226 ]   mysql
 msb_5_7_23               :   single         5.7.23    [5723 ]                mysql
```

Also available a tabular output:
```
$ dbdeployer sandboxes --flavor --header --table
.------------------------.--------------.---------.----------------------.--------.-------.--------.
|          name          |     type     | version |        ports         | flavor | nodes | locked |
+------------------------+--------------+---------+----------------------+--------+-------+--------+
| all_masters_msb_5_7_23 | all-masters  | 5.7.23  | [21224 21225 21226 ] | mysql  |     3 |        |
| msb_5_7_23             | single       | 5.7.23  | [5723 ]              | mysql  |     0 |        |
| rsandbox_5_7_23        | master-slave | 5.7.23  | [19024 19025 19026 ] | mysql  |     2 |        |
'------------------------'--------------'---------'----------------------'--------'-------'--------'
```

A new option `--full-info` corresponds to all the above (`--flavor --header --table`)
