### ISSUE TITLE
MariaDB Galera cluster topology

### ISSUE THREAD

**Issue by stedounet** [datacharmer/dbdeployer#77]
Hi !

I saw https://github.com/datacharmer/dbdeployer/issues/19 has been closed after PXC support

We still lack the possibility to create Galera clusters, is it planned ? It would really make dbdeployer complete to compare engines

Thank you, have a good day !

**Comment by datacharmer** [comment]
I don't plan to do it myself, but [I am open to contributions!](https://github.com/datacharmer/dbdeployer/blob/master/CONTRIBUTING.md)

**Comment by stedounet** [comment]
Thanks for your fast answer !
