### ISSUE TITLE
Suggestion: `dbdeployer deploy <...> --skip-start`

### ISSUE THREAD

**Issue by shlomi-noach** [datacharmer/dbdeployer#8]
I'd like to be able to create a sandbox setup (e.g. `replication`) but without auto-starting the servers. Is this possible? I suggest the `--skip-start` flag.

**Comment by datacharmer** [comment]
I think it is doable. 
However, a ``replication`` sandbox deployed with ``--skip-start`` will leave all the servers in an unpleasant condition, as they can't load the pre-defined users.

**Comment by datacharmer** [comment]
This issue was resolved in [version 1.2.0](https://github.com/datacharmer/dbdeployer/releases/tag/1.2.0). Please see the documentation about skipping server start for details on how to use it.
