### ISSUE TITLE
Exec format error on Windows Subsystem for Linux - Ubuntu

### ISSUE THREAD

**Issue by kappakun49** [datacharmer/dbdeployer#82]
I installed dbdeployer on Windows Subsystem for Linux - Ubuntu using the installation instructions provided:
```
$ VERSION=1.32.0
$ OS=linux
$ origin=https://github.com/datacharmer/dbdeployer/releases/download/v$VERSION
$ wget $origin/dbdeployer-$VERSION.$OS.tar.gz
$ tar -xzf dbdeployer-$VERSION.$OS.tar.gz
$ chmod +x dbdeployer-$VERSION.$OS
$ sudo mv dbdeployer-$VERSION.$OS /usr/local/bin/dbdeployer
```
It installs without any issue. However, when I try to run it, I get the following error:

`-bash: /usr/local/bin/dbdeployer: cannot execute binary file: Exec format error`

System Info:
```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
```

Architecture:

`x86_64`

**Comment by datacharmer** [comment]
Hi.
Thanks for reporting the issue. Unfortunately, I don't have any Windows system at my disposal, [nor do I want to have one](https://github.com/datacharmer/dbdeployer/blob/master/docs/features.md).
You may try to compile the source in your system, but I won't be able to offer much assistance there.

I can tell you that I regularly run those binaries on Ubuntu 18.04 and they work just fine.

Please try the same operation in a Docker container and you will see it working.

**Comment by kappakun49** [comment]
I did try other options and they do work fine. I'll try to compile the source in my system and see it that helps out. Else, I am just going to use Virtual box instead.

**Comment by datacharmer** [comment]
Please see [the instructions on how to compile](https://github.com/datacharmer/dbdeployer/blob/master/CONTRIBUTING.md) as a starting point.

**Comment by kappakun49** [comment]
Thanks
