### ISSUE TITLE
About a PXC related global

### ISSUE THREAD

**Issue by stedounet** [datacharmer/dbdeployer#87]
Hello

PXC flavor minimum version is set at 5.7.14, but 5.6.x versions do exist and can be downloaded from Percona. I hit this as I tried to use a 5.6 tar

Is there any reason I don't know ?

Thanks

**Comment by datacharmer** [comment]
The reason is that I was not given deployment instructions that work with 5.6. 
If you have changes that can be used to extend the deployability to 5.6 without breaking the existing code, I am willing to consider them.

**Comment by stedounet** [comment]
Ok thank you, I did not think about it and I will consider trying it

**Comment by datacharmer** [comment]
The fix for issue #92 will also solve this problem

**Comment by datacharmer** [comment]
This issue has been addressed in release 1.42.0.
The initialization commands are now in a template, which can be edited and reused as needed.
