### ISSUE TITLE
Unexpected "test" replication user on replication master

### ISSUE THREAD

**Issue by shlomi-noach** [datacharmer/dbdeployer#9]
When setting up a replication snadbox, as follows:

```
dbdeployer deploy replication 5.7.21 --nodes 7 --gtid --my-cnf-options log_slave_updates --my-cnf-options log_bin --my-cnf-options binlog_format=ROW --my-cnf-options performance_schema=0
```

I see the following:

```
$ ./m -e "select User_name,User_password from mysql.slave_master_info;"
+-----------+---------------+
| User_name | User_password |
+-----------+---------------+
| test      |               |
+-----------+---------------+
```

While on replicas the value is as expected:
```
$ ./s1 -e "select User_name,User_password from mysql.slave_master_info;"
+-----------+---------------+
| User_name | User_password |
+-----------+---------------+
| rsandbox  | rsandbox      |
+-----------+---------------+
```

The fact the master _has_ a username/password combo is confusing to begin with, and causes for further misunderstandings. In my particular use case, `orchestrator` sees the master's credentials and _assumes_ the master _has_ credentials and that they must be correct.

Suggestion: make the username `''` on the master.

**Comment by datacharmer** [comment]
I can't reproduce this issue. 
dbdeployer does not create a user "test". Look at the file ``grants.mysql`` in the master to verify it.

    $ dbdeployer deploy replication 5.7.21 --nodes 7 --gtid \
        --my-cnf-options log_slave_updates --my-cnf-options log_bin \
        --my-cnf-options binlog_format=ROW \
        --my-cnf-options performance_schema=0 --concurrent
    $HOME/sandboxes/rsandbox_5_7_21/initialize_slaves
    initializing slave 1
    initializing slave 2
    initializing slave 3
    initializing slave 4
    initializing slave 5
    initializing slave 6
    Replication directory installed in $HOME/sandboxes/rsandbox_5_7_21
    run 'dbdeployer usage multiple' for basic instructions'

    ~/sandboxes/rsandbox_5_7_21/use_all "select User_name,User_password from mysql.slave_master_info;"
    # master
    # server: 1
    User_name   User_password
    rsandbox    rsandbox
    # server: 2
    User_name   User_password
    rsandbox    rsandbox
    # server: 3
    User_name   User_password
    rsandbox    rsandbox
    # server: 4
    User_name   User_password
    rsandbox    rsandbox
    # server: 5
    User_name   User_password
    rsandbox    rsandbox
    # server: 6
    User_name   User_password
    rsandbox    rsandbox

**Comment by shlomi-noach** [comment]
Looking into what reproduces this.

**Comment by shlomi-noach** [comment]
This was caused by running

```
./use_all "stop slave; change master to master_auto_position=1; start slave;"
```

Closing this issue since `dbdeployer` itself is not the source of problem.
