### ISSUE TITLE
Add xtrabackup support for topology=pxc

### ISSUE THREAD

**Issue by ihanick** [datacharmer/dbdeployer#92]
**The problem**
PXC 8.0 requests xtrabackup SST method:
https://www.percona.com/downloads/TESTING/Percona-XtraDB-Cluster-8.0/
2019-09-19T03:15:04.829660Z 0 [ERROR] [MY-000000] [WSREP] Percona-XtraDB-Cluster doesn't support SST through rsync. Please switch to use xtrabackup-v2.

**Solution**
xtrabackup and mariabackup (or even MEB) could be also unpacked to opt in order to use a specific backup program version with dbdeployer replication installation. Or even have ability to provide a link/filepath to the backup to get a specific database restored by specific version of backup program.

**Alternative**
provide ability to run hooks during deploy. e.g. "before-start" should allow to replace wsrep_sst_method=rsync with wsrep_sst_method=xtrabackup-v2; "after-first-node-start": create a user for SST

**Comment by datacharmer** [comment]
Hi,
Thanks for reporting this issue.

There is, I believe, another solution, which is more in line with dbdeployer way of automating things.

Currently, the few lines of configuration file that contain the PXC setup, including `wsrep_sst_method=rsync`, are not in a template, but hard-coded.

Moving these lines into a template will allow users to [modify the template](https://github.com/datacharmer/dbdeployer#sandbox-customization) (either on-the-fly or permanently) and add or remove the elements that they see fit.

It is not a complicated change, but it will probably have to wait a few weeks for implementation.

**Comment by ihanick** [comment]
dbdeployer actually works with xtrabackup:
dbdeployer-1.37.0.linux deploy --topology=pxc replication 8.0.15 --my-cnf-options="wsrep_sst_method=xtrabackup-v2"

PXC 8.0 is not recognising wsrep_sst_auth option, loose- prefix allows to convert unknown parameter to warning.

diff --git a/sandbox/pxc_replication.go b/sandbox/pxc_replication.go
index 3848316..681e6ae 100644
--- a/sandbox/pxc_replication.go
+++ b/sandbox/pxc_replication.go
@@ -36,7 +36,7 @@ wsrep_cluster_address=__GROUP_COMMUNICATION__
 wsrep_node_incoming_address=127.0.0.1
 wsrep_provider_options=gmcast.listen_addr=tcp://127.0.0.1:__GROUP_PORT__
 wsrep_sst_method=rsync
-wsrep_sst_auth=root:
+loose_wsrep_sst_auth=root:

There is also startup problem, not related directly to dbdeployer:
--- Percona-XtraDB-Cluster_8.0.15.5-27dev.4.2_Linux.x86_64.ssl102/bin/wsrep_sst_common	2019-09-16 16:59:21.000000000 -0400
+++ opt/mysql/8.0.15/bin/wsrep_sst_common	2019-09-19 01:32:35.248738895 -0400
@@ -483,7 +483,7 @@ function wait_for_mysqld_startup()
             return 3
         fi
 
-        $mysqladmin_path ping --socket=$mysqld_socket &> /dev/null
+        $mysqladmin_path --defaults-file="${WSREP_SST_OPT_CONF}" --socket=$mysqld_socket ping &> /dev/null
         errcode=$?
         [[ $errcode -eq 0 ]] && break

**Comment by datacharmer** [comment]
Even if there is a workaround now, I'll keep this issue open until the hard-coded options become a template.

I haven't tested with PXC 8.0 yet. This change will make further enhancements easier to add.

**Comment by datacharmer** [comment]
This issue has been addressed in release 1.42.0.
The initialization commands are now in a template, which can be edited and reused as needed.

**Comment by datacharmer** [comment]
dbdeployer 1.46.0 can deploy PXC 8.0 without additional options.

**Comment by datacharmer** [comment]
[dbdeployer 1.47.0](https://github.com/datacharmer/dbdeployer/releases/tag/v1.47.0) works with PXC8.0.18 out of the box
